### ISSUE TITLE
CLI request hash for nonce always empty

### ISSUE THREAD

**Issue by sethjback** [Dentity-Development/dentity-ecosystems-sdk#431] opened 2022-02-03 00:44 UTC
using `&request.get_ref().to_vec()` does not return the serialized protobuf message bytes, and thus the blake3 hash is always the same (hash of an empty byte array):

https://github.com/trinsic-id/sdk/blob/eb136fb0a7bfd84e49a3cc38f5d97af84625b16e/cli/src/services/config.rs#L262-L270

Looks like tonic uses `into_inner` to return the message (as opposed to the metadata) and can be used to serialize the proto bytes.

https://docs.rs/tonic/0.6.2/tonic/struct.Request.html#method.into_inner

**Comment by sethjback** [comment] 2022-02-03 18:01
Root issues is that the tonic interceptor is not receiving the `message` payload in the call.

The correct method to use for getting the encoded bytes of the call is `&request.get_ref().encode_to_vec()`

**Comment by sethjback** [comment] 2022-02-08 18:34
Issue with the empty nonce hash is not just the `encode_to_vec()` call (which will now correctly return the hash), but rather that the tonic `request` `message` field is always empty, thus the hash is always the same (an empty byte array). 

I did some initial looking into why the message in this interceptor is empty but wasn't able to completely track it down (was focusing more on the protobuf field order issue)

**Comment by tmarkovski** [comment] 2022-02-08 19:40
Interesting, could it be that the interceptor fires a little too soon?

**Comment by sethjback** [comment] 2022-02-08 20:06
I don't think so - I was actually never able to get an interceptor to have the message available in it, even following the doc's example, so I wonder if it is something in tonic. If you look at the `request` that is generated by the sdk right before it is returned from the gRPC function the message is there and you can get a valid hash. If you look at the request when it hits the interceptor, it is empty. 

I even went so far as to create the BLAKE3 hash of the request in the gRPC function, add it to the request metadata, extract it in the interceptor, and build the nonce from there (so I could troubleshoot the protobuf serializing). So the metadata is getting passed through just fine, but not the actual message. Which is odd because the message makes it out over the wire just fine...

**Comment by janpieterz** [comment] 2022-10-13 17:12
@tmarkovski will take a peek if this is still an issue :)
I

**Comment by janpieterz** [comment] 2022-11-22 10:34
@tmarkovski Could you take that peek? ;)

**Comment by tmarkovski** [comment] 2022-11-22 13:32
Neither `into_inner()` nor `get_ref()` return the actual message, they are both of type `()`. The interceptor logic as designed, only intercepts and modifies the metadata dictionary, which is then appended to the original request message by tonic, it doesn't actually pass the message.
Since we don't enforce the hash logic on the server anyway, I think we can close this.

**Closed as not planned** 2022-11-22 13:33 UTC
Labels: bug
