### ISSUE TITLE
Add SDK language and version to User-Agent header

### ISSUE THREAD

**Issue by janpieterz** [Dentity-Development/dentity-ecosystems-sdk#839] opened 2022-07-05 15:34 UTC
- Add for each language
- Add to log context for all request logs

**Comment by fundthmcalculus** [comment] 2022-07-05 20:04
closing as duplicate of #845 (which has the SDK change request template)

**Closed as not planned by fundthmcalculus** 2022-07-05 20:04 UTC

**Comment by janpieterz** [comment] 2022-07-12 12:37
Will archive instead so it doesn't appear on a board.
