### ISSUE TITLE
Add Support for Dart as a Language

### ISSUE THREAD

**Issue by fundthmcalculus** [Dentity-Development/dentity-ecosystems-sdk#667] opened 2022-05-23 20:27 UTC
- [ ] build/release/test github action yaml files
- [ ] Add entry `dart` to the SDK Language change request issue template
- [ ] Wrap existing services
- [ ] update `generate_protos.py` action

**Comment by geel9** [comment] 2022-05-24 15:15
Duplicate of #668

**Closed as not planned by geel9** 2022-05-24 15:15 UTC
